name: CI Process
on: [ push ]

jobs:
  hello_world:
    name: "Hello World"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Echo"
        run: echo "Hello World"
